version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpass
      POSTGRES_DB: iotdb
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: iot-ingestor # Use custom username
      RABBITMQ_DEFAULT_PASS: iot-ingestor-pass # Set a custom password
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  mqtt:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
networks:
  default:
    driver: bridge
