// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SensorDatum struct {
	ID          int64
	DeviceID    pgtype.UUID
	Timestamp   pgtype.Timestamptz
	Temperature pgtype.Float8
	Humidity    pgtype.Float8
}
